### ISSUE TITLE
json language conflict with jsonc

### ISSUE THREAD

**Issue by luckydye** [biomejs/biome-zed#11]
So zed has no specific language for .jsonc files, all json files are interpreted as jsonc under "JSON".
Now that the biome extensions uses "json" to interpret json files, we get this stuff:

<img width="779" alt="image" src="https://github.com/biomejs/biome-zed/assets/10381895/e1757ce3-2e3d-487d-99f4-f307efa8fbe8">

We should probably use jsonc for all json files. Though not sure who is right here.

**Comment by ematipico** [comment]
I noticed that too. However, that's the settings zed file, so I suppose zed does the same thing as VSCode.

If you opened another JSON file, you wouldn't have these errors. I suppose we'll have to add a new expectation

**Comment by Sec-ant** [comment]
To address potential future language-detection problems, we may want to support using [filepath glob patterns](https://code.visualstudio.com/docs/languages/overview#_can-i-map-additional-file-extensions-to-a-language) and the [first line of the file](https://code.visualstudio.com/api/references/contribution-points#contributes.languages) to detect languages just like what VSCode does. We can also learn it from other editors or tools like Prettier.

**Comment by luckydye** [comment]
> I noticed that too. However, that's the settings zed file, so I suppose zed does the same thing as VSCode.
> 
> If you opened another JSON file, you wouldn't have these errors. I suppose we'll have to add a new expectation

Yes, but zed actually implies all json files are jsonc, not just the settings files. 
I think it would be best to actually have a separate JSONC langauge in the editor to control this.

**Comment by silvenon** [comment]
FWIW i'm getting similar errors in `biome.jsonc` file, I guess because Zed doesn't recognize those. In my [`file_types`](https://zed.dev/docs/configuring-zed#file-types) I configured `"JSON": ["json", "jsonc"]`, which took care of the syntax highlighting, but the didn't resolve the error. I'm not sure if it's related to this.

![Screenshot 2024-05-13 at 22 24 06](https://github.com/biomejs/biome-zed/assets/471278/e704ca90-4601-41f9-9cf1-ebe2b839f2ec)

**Comment by xcrap** [comment]
Any forecast on this matter? 
I wanted to switch to Biome in Zed and VSCode :)

**Comment by ematipico** [comment]
There's nothing much to do. You'll have to use a configuration file, and enable JSONC features in the parser options

**Comment by xcrap** [comment]
Or... Zed could add the support for JSONC and we could enable the default formatter for those instead of Biome... without having to create a config file for every project :)

**Comment by ematipico** [comment]
Feel free to file an issue in their repository

**Comment by xcrap** [comment]
So apparently it's gonna happen :)

**Comment by luckydye** [comment]
Is fixed in Zed 0.143.0

**Comment by bingoct** [comment]
<img width="2380" height="1349" alt="Image" src="https://github.com/user-attachments/assets/5f76c328-49cf-44e1-83c3-35f96389b014" />

# Appearance

Upon initially opening settings.json, the language mode defaults to jsonc, but the issue persists. Clicking the language selector and manually re-selecting jsoncresolves the conflict; however, after saving or editing the file, the error End of file expectedreappears.

# env

os/platform: win10 22H2 build 19045.6466
zed version：1.7.2
biome extension version： v0.3.1
