### ISSUE TITLE
Can't get Biome to organize imports on save

### ISSUE THREAD

**Issue by micthiesen** [biomejs/biome-zed#35]
These are my current language settings but I've tried a bunch of variations:

```json
  "languages": {
    "TypeScript": {
      "language_servers": [
        "!typescript-language-server",
        "!eslint",
        "vtsls",
        "biome"
      ],
      "preferred_line_length": 88,
      "wrap_guides": [88],
      "format_on_save": "on",
      "formatter": {
        "language_server": {
          "name": "biome"
        }
      },
      "code_actions_on_format": {
        "source.fixAll.biome": true,
        "source.organizeImports.biome": true
      }
    }
  }
```

I've tried on `Zed Preview 0.146.1` and also `Zed 0.145.1`.

I can trigger the code action inside the editor so I believe the LSP is set up properly:
![CleanShot 2024-07-29 at 21 59 38](https://github.com/user-attachments/assets/2a3cb2c8-f711-4926-81c3-2d8d44e3191d)

Also formatting seems to work. Any suggestions would be appreciated.

**Comment by ematipico** [comment]
Does the CLI work? If it is, then I think the issue is Zed. Maybe try to check the Daemon logs and see if Biome actually calls the import sorting.

**Comment by chungweileong94** [comment]
I realized this thing, most likely related to this issue #26, where I thought the issue was already fixed, but apparently something else happen.

**Comment by micthiesen** [comment]
@ematipico  Yep `biome check --write .` does sort the imports for me. I don't see anything relevant in the Zed logs, not sure how to check the Biome LSP logs tbh.

@chungweileong94 I saw that issue which is why I tried the Zed Preview. Unfortunately it didn't fix it for me.

**Comment by chungweileong94** [comment]
I pretty sure this is cause by Zed, as I haven't update my Biome version for a long time. The only thing that changed is Zed and Biome extension, even if I downgrade the extension, the issue still persist.

**Comment by micthiesen** [comment]
Ok makes sense. I created an issue there and I'll close this one. Thanks!

**Comment by ematipico** [comment]
That's where the logs are stored: https://biomejs.dev/guides/editors/create-a-plugin/#daemon-logs

**Comment by elawad** [comment]
FYI after some trial and error, I was able to get sorting to work on save. 
Had to add `source.organizeImports` below.

```jsonp
// settings.json
"code_actions_on_format": {
    "source.fixAll.biome": true,
    "source.organizeImports.biome": true,
    "source.organizeImports": true
  },
````

**Comment by chungweileong94** [comment]
> Had to add source.organizeImports below.

I don't think so though, this is to tell Zed to use the TypeScript LSP organizer import action. So even though it will be sorted, but it is not Biome import sorting.

**Comment by elawad** [comment]
Looks to be fixed now. See https://github.com/biomejs/biome-zed/issues/46#issuecomment-2365207074
